dataset:
  name: bird
  num_classes: 200
  pre_size: 80
  image_size: 64

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/fine-grained/processed/images_finegrained
    imglist_pth: ./data/fine-grained/processed/benchmark_imglist/train_CUB_200_2011.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/fine-grained/processed/images_finegrained
    imglist_pth: ./data/fine-grained/processed/benchmark_imglist/test_CUB_200_2011.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/fine-grained/processed/images_finegrained
    imglist_pth: ./data/fine-grained/processed/benchmark_imglist/test_CUB_200_2011.txt
    batch_size: 128
    shuffle: False
